### ISSUE TITLE
Documentation on Read the Docs is unavailable

### ISSUE THREAD

**Issue by diogobernini** [jgorset/fandjango#111]
https://readthedocs.org/docs/fandjango points me to "page does not exist".

**Comment by jgorset** [comment]
Oh, it seems they moved it to https://readthedocs.org/projects/fandjango/. Thanks!

**Comment by jgorset** [comment]
Fixed in https://github.com/jgorset/fandjango/commit/3c5f66eaab35830c94e42d2ab533e041ee28e79b.
