### ISSUE TITLE
pip install fandjango

### ISSUE THREAD

**Issue by geekscrapy** [jgorset/fandjango#112]
Got the following error when pip installing

    Collecting fandango
    Using cached fandango-12.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    
    
    To install as system package:
    
      python setup.py install
    
    To install as local package, just run:
    
      mkdir /tmp/builds/
      python setup.py install --root=/tmp/builds
      /tmp/builds/usr/bin/$DS -? -v4
    
    To tune some options:
    
      RU=/opt/control
      python setup.py egg_info --egg-base=tmp install --root=$RU/files --no-compile     --install-lib=lib/python/site-packages --install-scripts=ds
    
    -------------------------------------------------------------------------------
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n1/wd93plnd3dx1f4g9kr_6dc8m0000gn/T/pip-build-6aiVcS/fandango/setup.py", line 29, in <module>
        release = open('fandango/VERSION').read()
    IOError: [Errno 2] No such file or directory: 'fandango/VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n1/wd93plnd3dx1f4g9kr_6dc8m0000gn/T/pip-build-6aiVcS/fandango/`

**Comment by jgorset** [comment]
Hi @geekscrapy! You're trying to install `fandango`, but this package is called `fandjango`. :wink:

**Comment by geekscrapy** [comment]
Thanks, good thing it didn't install then...!
