### ISSUE TITLE
infinite loop with login required

### ISSUE THREAD

**Issue by markokruijer** [jgorset/fandjango#32]
I'm having a problem with getting users logged in through facebook. I've set up an app in my developers page, copied the secret key and app_id to my settings and put the login decorator on my page. 
If i know browse to that page, it redirects me to facebook, requesting login and to give the app permission to my account.

So far so good, however when this has been done the page keeps redirecting and i see the code GET parameter changing all the time. I think there is a misconfiguration somewhere, but I'm not aware of the debugging options that I should us here.

What's the best way to approach this problem with fandjango?

**Comment by crajiengg** [comment]
I faced the same issue. It looped infinite times. It may help others. so Iam posting my solution. By changing middleware from 'FacebookMiddleware'  to 'FacebookWebMiddleware', problem solved for me.
